name: electrs CI

on: [push, pull_request]

jobs:
  electrs:
    name: electrs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        uses: actions-rs/toolchain@v1
        with:
          components: rustfmt, clippy
          profile: minimal
          override: true

      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
